# Generated by Django 4.1.1 on 2022-11-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('currency', models.CharField(choices=[('rub', 'RUB'), ('usd', 'USD')], default='rub', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(choices=[('rub', 'RUB'), ('usd', 'USD')], default='rub', max_length=3)),
                ('price', models.IntegerField()),
                ('items', models.ManyToManyField(to='application.item')),
            ],
        ),
    ]
